debug: true
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.mainproject012: debug
    org.springframework.r2dbc.core: debug

spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:mysql://localhost:3306/matp
    username: bonoj
    password: thisisTESTpw!#%
  sql.init.mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "${OAUTH2_CLIENT_ID}"
            clientSecret: "${OAUTH2_CLIENT_PW}"
          naver:
            client-name: Naver
            client-id: "${OAUTH2_CLIENT_ID_NAVER}"
            client-secret: "${OAUTH2_CLIENT_PW_NAVER}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          kakao:
            client-name: Kakao
            client-id: "${OAUTH2_CLIENT_ID_KAKAO}"
            client-secret: "${OAUTH2_CLIENT_PW_KAKAO}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 420

